[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    bogde/HX711@^0.7.5
    sandeepmistry/LoRa@^0.8.0
    bblanchon/ArduinoJson@^7.0.4
    ottowinter/ESPAsyncWebServer-esphome@^3.1.0
    ayushsharma82/AsyncElegantOTA@^3.1.5

build_flags =
    -DCORE_DEBUG_LEVEL=3

monitor_filters =
    esp32_exception_decoder
